### ISSUE TITLE
Error DROWN

### ISSUE THREAD

**Issue by arbazkiraak** [hahwul/a2sv#12]
Hey ,

Thanks for the update , Previous issue Resolved ,

But Came with Another Problem.

[RES] OpenSSL FREAK :: 0x00
[INF] Scan OpenSSL LOGJAM..
- [LOG] IP Check Ok.
- [LOG] Start SSL Connection / Gathering Information
- [LOG] Ending Get Information
- [LOG] 'Cipher is DEH' not in Response
  [RES] OpenSSL LOGJAM :: 0x00
  [INF] Scan SSLv2 DROWN..
  Traceback (most recent call last):
  File "a2sv.py", line 315, in <module>
    runScan(checkVun)
  File "a2sv.py", line 165, in runScan
    drown_result = m_drown_run(targetIP,port)
  File "/root/Desktop/Pentest-Suite/SSL/a2sv/module/M_drown.py", line 32, in m_drown_run
    server_hello = s.recv(10*1024)
  socket.error: [Errno 104] Connection reset by peer

**Comment by arbazkiraak** [comment]
+1:  Working Fine Now :) No Problem!
