### ISSUE TITLE
Run Error :: "-p command, I get the error that it is not an Integer"

### ISSUE THREAD

**Issue by hahwul** [hahwul/a2sv#2]
[INF] Scan CCS Injection..
Traceback (most recent call last):
  File "/home/noon/Noon/a2sv/a2sv.py", line 163, in <module>
    runScan(checkVun)
  File "/home/noon/Noon/a2sv/a2sv.py", line 78, in runScan
    ccs_result = m_ccsinjection_run(targetIP,port)
  File "/home/noon/Noon/a2sv/module/M_ccsinjection.py", line 329, in m_ccsinjection_run
    strLogPre = "[%s] %s:%d" % (strVer,strHost,iPort)
TypeError: %d format: a number is required, not str

**Comment by hahwul** [comment]
Fixed Bug
(A2SV v1.2.1)
