### ISSUE TITLE
Heartbleed check throws error 104

### ISSUE THREAD

**Issue by Blkzer0** [hahwul/a2sv#30]
If i try to run heart check, i get error. Every other check function works fine. The script is updated to latest version. You mentioned that you patched it but im still getting this error. If i try to run all the check s except heart, it will still run heart and return error.  Heres the error log:

```
 - [LOG] Sending Client Hello...
 - [LOG] Waiting for Server Hello...
 - [LOG] Sending heartbeat request..
Traceback (most recent call last):
  File "a2sv.py", line 421, in <module>
    runScan(checkVun)
  File "a2sv.py", line 147, in runScan
    heartbleed_result = m_heartbleed_run(targetIP,port,displayMode)
  File "/home/blkzer0/Desktop/scripts/scanners/a2sv/module/M_heartbleed.py", line 196, in m_heartbleed_run
    check(target,port,"","","",displayMode)
  File "/home/blkzer0/Desktop/scripts/scanners/a2sv/module/M_heartbleed.py", line 188, in check
    response = hit_hb(s,dumpf, host, quiet)
  File "/home/blkzer0/Desktop/scripts/scanners/a2sv/module/M_heartbleed.py", line 97, in hit_hb
    typ, ver, pay = recvmsg(s)
  File "/home/blkzer0/Desktop/scripts/scanners/a2sv/module/M_heartbleed.py", line 83, in recvmsg
    hdr = recvall(s, 5)
  File "/home/blkzer0/Desktop/scripts/scanners/a2sv/module/M_heartbleed.py", line 74, in recvall
    data = s.recv(remain)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by hahwul** [comment]
Thank you for sending issue. I'll check.

**Comment by Visalyputra** [comment]
any update regarding for this bug?

**Comment by skaunited** [comment]
there no update for this bug?

**Comment by Ruzomuzo** [comment]
please dude do something about this
