### ISSUE TITLE
socket.error: [Errno 104] Connection reset by peer in M_heartbleed.py

### ISSUE THREAD

**Issue by srkgupta** [hahwul/a2sv#45]
Can we handle this if the connection is reset by peer during the Heartbleed check? 

```
Traceback (most recent call last):
  File "/root/scripts/a2sv/a2sv.py", line 418, in <module>
    runScan(checkVun)
  File "/root/scripts/a2sv/a2sv.py", line 177, in runScan
    heartbleed_result = m_heartbleed_run(targetIP,port,displayMode)
  File "/root/scripts/a2sv/module/M_heartbleed.py", line 196, in m_heartbleed_run
    check(target,port,"","","",displayMode)
  File "/root/scripts/a2sv/module/M_heartbleed.py", line 172, in check
    version = parseresp(s)
  File "/root/scripts/a2sv/module/M_heartbleed.py", line 136, in parseresp
    typ, ver, pay = recvmsg(s)
  File "/root/scripts/a2sv/module/M_heartbleed.py", line 83, in recvmsg
    hdr = recvall(s, 5)
  File "/root/scripts/a2sv/module/M_heartbleed.py", line 74, in recvall
    data = s.recv(remain)
```

**Comment by nourmuj** [comment]
I have received the same error message. Has anyone found a solution to this problem? 

```bash
Traceback (most recent call last):
  File "/root/tools/a2sv/a2sv.py", line 425, in <module>
    runScan(checkVun)
  File "/root/tools/a2sv/a2sv.py", line 181, in runScan
    heartbleed_result = m_heartbleed_run(targetIP,port,displayMode)
  File "/root/tools/a2sv/module/M_heartbleed.py", line 196, in m_heartbleed_run
    check(target,port,"","","",displayMode)
  File "/root/tools/a2sv/module/M_heartbleed.py", line 188, in check
    response = hit_hb(s,dumpf, host, quiet)
  File "/root/tools/a2sv/module/M_heartbleed.py", line 97, in hit_hb
    typ, ver, pay = recvmsg(s)
  File "/root/tools/a2sv/module/M_heartbleed.py", line 83, in recvmsg
    hdr = recvall(s, 5)
  File "/root/tools/a2sv/module/M_heartbleed.py", line 74, in recvall
    data = s.recv(remain)
socket.error: [Errno 104] Connection reset by peer

```
