### ISSUE TITLE
[Dev] Making install script / install menual

### ISSUE THREAD

**Issue by hahwul** [hahwul/a2sv#5]
[Dev] Making install script / install menual
- install.sh
- INSTALL.md

**Comment by CheatRAM** [comment]
Got  : 
`
Traceback (most recent call last):
  File "a2sv.py", line 281, in <module>
    runScan(checkVun)
  File "a2sv.py", line 148, in runScan
    poodle_result = m_poodle_run(targetIP,port)
  File "/root/Desktop/a2sv/a2sv/module/M_poodle.py", line 23, in m_poodle_run
    result = test_server(hostname, port, ssl.PROTOCOL_SSLv3, timeout)
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
`
With command : 
`python a2sv.py -t <targetname>`

**Comment by hahwul** [comment]
Updated.
